insert into item(name, category) values ('chatgpt5', 'ai_tool');
insert into item(name, category) values ('NOTION AI', 'ai_tool');
insert into item(name, category) values ('BIXBY', 'ai_tool');
insert into item(name, category) values ('GEMINI', 'ai_tool');
insert into item(name, category) values ('chatgpt', 'ai_tool');
insert into item(name, category) values ('Grammarly', 'ai_tool');
insert into item(name, category) values ('AITable', 'ai_tool');
insert into item(name, category) values ('10Web', 'ai_tool');
insert into item(name, category) values ('AI Detector Pro', 'ai_tool');
insert into item(name, category) values ('AI Lawyer', 'ai_tool');
insert into item(name, category) values ('AI Room Planner', 'ai_tool');
insert into item(name, category) values ('AI Voice Detector', 'ai_tool');
insert into item(name, category) values ('AIPRM', 'ai_tool');
insert into item(name, category) values ('AISEO', 'ai_tool');
insert into item(name, category) values ('AISEO Art', 'ai_tool');
insert into item(name, category) values ('AdCreative.ai', 'ai_tool');
insert into item(name, category) values ('Adalo', 'ai_tool');
insert into item(name, category) values ('Adobe Express', 'ai_tool');
insert into item(name, category) values ('Adobe Firefly', 'ai_tool');
insert into item(name, category) values ('Adobe Podcast', 'ai_tool');
insert into item(name, category) values ('Adobe Sensei', 'ai_tool');
insert into item(name, category) values ('AimReply', 'ai_tool');
insert into item(name, category) values ('Alphana', 'ai_tool');
insert into item(name, category) values ('Altered', 'ai_tool');
insert into item(name, category) values ('AnimeGenius', 'ai_tool');
insert into item(name, category) values ('Apify', 'ai_tool');
insert into item(name, category) values ('Aragon', 'ai_tool');
insert into item(name, category) values ('Artflow', 'ai_tool');
insert into item(name, category) values ('Artsmart AI', 'ai_tool');
insert into item(name, category) values ('Audio writer', 'ai_tool');
insert into item(name, category) values ('Audo', 'ai_tool');
insert into item(name, category) values ('Aura AI', 'ai_tool');
insert into item(name, category) values ('AutoShorts', 'ai_tool');
insert into item(name, category) values ('Automata', 'ai_tool');
insert into item(name, category) values ('Bannerbear', 'ai_tool');
insert into item(name, category) values ('BatchTable', 'ai_tool');
insert into item(name, category) values ('BeforeSunset AI', 'ai_tool');
insert into item(name, category) values ('Bertha AI', 'ai_tool');
insert into item(name, category) values ('BetterPic', 'ai_tool');
insert into item(name, category) values ('Biread', 'ai_tool');
insert into item(name, category) values ('Bizway', 'ai_tool');
insert into item(name, category) values ('Black Friday Deals', 'ai_tool');
insert into item(name, category) values ('Blaze', 'ai_tool');
insert into item(name, category) values ('Bodt', 'ai_tool');
insert into item(name, category) values ('Brain FM', 'ai_tool');
insert into item(name, category) values ('Brand24', 'ai_tool');
insert into item(name, category) values ('Browse AI', 'ai_tool');
insert into item(name, category) values ('Bubble AI', 'ai_tool');
insert into item(name, category) values ('Caspar AI', 'ai_tool');
insert into item(name, category) values ('Castmagic', 'ai_tool');
insert into item(name, category) values ('Catbird', 'ai_tool');
insert into item(name, category) values ('Chaindesk', 'ai_tool');
insert into item(name, category) values ('Chance AI', 'ai_tool');
insert into item(name, category) values ('Character AI', 'ai_tool');
insert into item(name, category) values ('ChatGPT', 'ai_tool');
insert into item(name, category) values ('ChatGPT Writer', 'ai_tool');
insert into item(name, category) values ('ChatPlayground', 'ai_tool');
insert into item(name, category) values ('Cheatlayer', 'ai_tool');
insert into item(name, category) values ('Chivvy', 'ai_tool');
insert into item(name, category) values ('Cleanvoice', 'ai_tool');
insert into item(name, category) values ('Clickup', 'ai_tool');
insert into item(name, category) values ('ClipBuddy', 'ai_tool');
insert into item(name, category) values ('Cliptalk', 'ai_tool');
insert into item(name, category) values ('Clockk', 'ai_tool');
insert into item(name, category) values ('CoachVox', 'ai_tool');
insert into item(name, category) values ('Coda AI', 'ai_tool');
insert into item(name, category) values ('CodeDesign', 'ai_tool');
insert into item(name, category) values ('Codeleaks', 'ai_tool');
insert into item(name, category) values ('CodiumAI', 'ai_tool');
insert into item(name, category) values ('Compose AI', 'ai_tool');
insert into item(name, category) values ('ContentBot', 'ai_tool');
insert into item(name, category) values ('ContentShake', 'ai_tool');
insert into item(name, category) values ('ContentStudio AI', 'ai_tool');
insert into item(name, category) values ('CopySpace', 'ai_tool');
insert into item(name, category) values ('CourseAI', 'ai_tool');
insert into item(name, category) values ('Coursebox AI', 'ai_tool');
insert into item(name, category) values ('Craiyon', 'ai_tool');
insert into item(name, category) values ('Creaitor', 'ai_tool');
insert into item(name, category) values ('Creatify', 'ai_tool');
insert into item(name, category) values ('Creatr', 'ai_tool');
insert into item(name, category) values ('Cuppa', 'ai_tool');
insert into item(name, category) values ('CustomGPT', 'ai_tool');
insert into item(name, category) values ('DET Practice', 'ai_tool');
insert into item(name, category) values ('Dante', 'ai_tool');
insert into item(name, category) values ('Dashworks', 'ai_tool');
insert into item(name, category) values ('Deblank', 'ai_tool');
insert into item(name, category) values ('Deciphr', 'ai_tool');
insert into item(name, category) values ('Decktopus', 'ai_tool');
insert into item(name, category) values ('DeepBrain', 'ai_tool');
insert into item(name, category) values ('DeepL', 'ai_tool');
insert into item(name, category) values ('Describely', 'ai_tool');
insert into item(name, category) values ('Descript', 'ai_tool');
insert into item(name, category) values ('DescriptionWise', 'ai_tool');
insert into item(name, category) values ('Devi AI', 'ai_tool');
insert into item(name, category) values ('DigitalFirst', 'ai_tool');
insert into item(name, category) values ('DimeADozen', 'ai_tool');
insert into item(name, category) values ('Divi AI', 'ai_tool');
insert into item(name, category) values ('Durable', 'ai_tool');
insert into item(name, category) values ('Dzine', 'ai_tool');
insert into item(name, category) values ('Eagle', 'ai_tool');
insert into item(name, category) values ('Easy Peasy', 'ai_tool');
insert into item(name, category) values ('Eclipse AI', 'ai_tool');
insert into item(name, category) values ('Ecommerce Prompts', 'ai_tool');
insert into item(name, category) values ('Elai', 'ai_tool');
insert into item(name, category) values ('Elementor AI', 'ai_tool');
insert into item(name, category) values ('Elephas', 'ai_tool');
insert into item(name, category) values ('ElevenLabs', 'ai_tool');
insert into item(name, category) values ('Eloise AI', 'ai_tool');
insert into item(name, category) values ('Email Magic', 'ai_tool');
insert into item(name, category) values ('Endless VN', 'ai_tool');
insert into item(name, category) values ('Exolyt', 'ai_tool');
insert into item(name, category) values ('FYLM.ai', 'ai_tool');
insert into item(name, category) values ('Fathom', 'ai_tool');
insert into item(name, category) values ('Feathery', 'ai_tool');
insert into item(name, category) values ('Fellow', 'ai_tool');
insert into item(name, category) values ('Filmora', 'ai_tool');
insert into item(name, category) values ('Fireflies', 'ai_tool');
insert into item(name, category) values ('Flowrite', 'ai_tool');
insert into item(name, category) values ('Followr', 'ai_tool');
insert into item(name, category) values ('Formula Bot', 'ai_tool');
insert into item(name, category) values ('Frame', 'ai_tool');
insert into item(name, category) values ('Framer', 'ai_tool');
insert into item(name, category) values ('Frase', 'ai_tool');
insert into item(name, category) values ('Freeflo', 'ai_tool');
insert into item(name, category) values ('Future Desk', 'ai_tool');
insert into item(name, category) values ('GPT zero', 'ai_tool');
insert into item(name, category) values ('GPTinf', 'ai_tool');
insert into item(name, category) values ('GPTkit', 'ai_tool');
insert into item(name, category) values ('Galaxy AI', 'ai_tool');
insert into item(name, category) values ('GetGenie', 'ai_tool');
insert into item(name, category) values ('GetResponse', 'ai_tool');
insert into item(name, category) values ('Ghost Writer', 'ai_tool');
insert into item(name, category) values ('GhostContent', 'ai_tool');
insert into item(name, category) values ('Github Autopilot', 'ai_tool');
insert into item(name, category) values ('Glasp', 'ai_tool');
insert into item(name, category) values ('Gling', 'ai_tool');
insert into item(name, category) values ('GoCharlie', 'ai_tool');
insert into item(name, category) values ('Google Workspace', 'ai_tool');
insert into item(name, category) values ('Guidejar', 'ai_tool');
insert into item(name, category) values ('Gummysearch', 'ai_tool');
insert into item(name, category) values ('HEIGHTS AI', 'ai_tool');
insert into item(name, category) values ('HIX Bypass', 'ai_tool');
insert into item(name, category) values ('Hansei', 'ai_tool');
insert into item(name, category) values ('Harpa AI', 'ai_tool');
insert into item(name, category) values ('HeadshotPro', 'ai_tool');
insert into item(name, category) values ('Hexofy', 'ai_tool');
insert into item(name, category) values ('Hexomatic', 'ai_tool');
insert into item(name, category) values ('Hexometer', 'ai_tool');
insert into item(name, category) values ('Hexowatch', 'ai_tool');
insert into item(name, category) values ('HeyGen', 'ai_tool');
insert into item(name, category) values ('Hify', 'ai_tool');
insert into item(name, category) values ('Hiver', 'ai_tool');
insert into item(name, category) values ('HookSounds AI Studio', 'ai_tool');
insert into item(name, category) values ('HoppyCopy', 'ai_tool');
insert into item(name, category) values ('Hotpot', 'ai_tool');
insert into item(name, category) values ('Hotreach AI', 'ai_tool');
insert into item(name, category) values ('Hubspot AI', 'ai_tool');
insert into item(name, category) values ('HypeAuditor', 'ai_tool');
insert into item(name, category) values ('HypeFury', 'ai_tool');
insert into item(name, category) values ('Hypernatural', 'ai_tool');
insert into item(name, category) values ('IMAI', 'ai_tool');
insert into item(name, category) values ('Icon', 'ai_tool');
insert into item(name, category) values ('InLinks', 'ai_tool');
insert into item(name, category) values ('InsightBaseAI', 'ai_tool');
insert into item(name, category) values ('InterviewSpark', 'ai_tool');
insert into item(name, category) values ('Inworld', 'ai_tool');
insert into item(name, category) values ('Jasper', 'ai_tool');
insert into item(name, category) values ('JoggAI', 'ai_tool');
insert into item(name, category) values ('Jupitrr', 'ai_tool');
insert into item(name, category) values ('KIVA', 'ai_tool');
insert into item(name, category) values ('Kafkai', 'ai_tool');
insert into item(name, category) values ('Katteb', 'ai_tool');
insert into item(name, category) values ('Keyword Insights', 'ai_tool');
insert into item(name, category) values ('KeywordsPeopleUse', 'ai_tool');
insert into item(name, category) values ('Klap', 'ai_tool');
insert into item(name, category) values ('Koala AI', 'ai_tool');
insert into item(name, category) values ('Kudra', 'ai_tool');
insert into item(name, category) values ('Lalal AI', 'ai_tool');
insert into item(name, category) values ('Landr', 'ai_tool');
insert into item(name, category) values ('Lately', 'ai_tool');
insert into item(name, category) values ('Leadpages AI Engine', 'ai_tool');
insert into item(name, category) values ('LearnWorlds AI', 'ai_tool');
insert into item(name, category) values ('LensGo', 'ai_tool');
insert into item(name, category) values ('Letterdrop', 'ai_tool');
insert into item(name, category) values ('Letterly', 'ai_tool');
insert into item(name, category) values ('Lexica', 'ai_tool');
insert into item(name, category) values ('Liner', 'ai_tool');
insert into item(name, category) values ('Linguix', 'ai_tool');
insert into item(name, category) values ('Link Whisper AI', 'ai_tool');
insert into item(name, category) values ('LogicLister', 'ai_tool');
insert into item(name, category) values ('Logo AI', 'ai_tool');
insert into item(name, category) values ('Looka', 'ai_tool');
insert into item(name, category) values ('Lovable', 'ai_tool');
insert into item(name, category) values ('Lovo', 'ai_tool');
insert into item(name, category) values ('Luma AI', 'ai_tool');
insert into item(name, category) values ('Luna', 'ai_tool');
insert into item(name, category) values ('Luna AI', 'ai_tool');
insert into item(name, category) values ('Lunacy by Icons8', 'ai_tool');
insert into item(name, category) values ('Lyro by Tidio', 'ai_tool');
insert into item(name, category) values ('Magai', 'ai_tool');
insert into item(name, category) values ('Magic Hour', 'ai_tool');
insert into item(name, category) values ('Magic Studio', 'ai_tool');
insert into item(name, category) values ('MagicReply', 'ai_tool');
insert into item(name, category) values ('Make', 'ai_tool');
insert into item(name, category) values ('Manatal', 'ai_tool');
insert into item(name, category) values ('Marketing Megaprompts', 'ai_tool');
insert into item(name, category) values ('Marketmuse', 'ai_tool');
insert into item(name, category) values ('Media.io', 'ai_tool');
insert into item(name, category) values ('Merlin', 'ai_tool');
insert into item(name, category) values ('MicMonster', 'ai_tool');
insert into item(name, category) values ('Midjourney Prompt Generator', 'ai_tool');
insert into item(name, category) values ('MimicPC', 'ai_tool');
insert into item(name, category) values ('MindPal', 'ai_tool');
insert into item(name, category) values ('Mixo', 'ai_tool');
insert into item(name, category) values ('Monic AI', 'ai_tool');
insert into item(name, category) values ('Monica', 'ai_tool');
insert into item(name, category) values ('Monkeebrain', 'ai_tool');
insert into item(name, category) values ('Moonbeam', 'ai_tool');
insert into item(name, category) values ('MosaChat-AI', 'ai_tool');
insert into item(name, category) values ('Motiva', 'ai_tool');
insert into item(name, category) values ('Mubert', 'ai_tool');
insert into item(name, category) values ('Munch', 'ai_tool');
insert into item(name, category) values ('Murf', 'ai_tool');
insert into item(name, category) values ('My GPT Wizard', 'ai_tool');
insert into item(name, category) values ('Nanonets', 'ai_tool');
insert into item(name, category) values ('Nara', 'ai_tool');
insert into item(name, category) values ('Nekton AI', 'ai_tool');
insert into item(name, category) values ('Netus AI', 'ai_tool');
insert into item(name, category) values ('Neural Love', 'ai_tool');
insert into item(name, category) values ('NeuralNewsletters', 'ai_tool');
insert into item(name, category) values ('Neuraltext', 'ai_tool');
insert into item(name, category) values ('Notion AI', 'ai_tool');
insert into item(name, category) values ('NovelAI', 'ai_tool');
insert into item(name, category) values ('Numerous AI', 'ai_tool');
insert into item(name, category) values ('Olympia', 'ai_tool');
insert into item(name, category) values ('One Click Human', 'ai_tool');
insert into item(name, category) values ('OpusClip', 'ai_tool');
insert into item(name, category) values ('Originality AI', 'ai_tool');
insert into item(name, category) values ('OutGrow', 'ai_tool');
insert into item(name, category) values ('PDF Flex', 'ai_tool');
insert into item(name, category) values ('PDF ai', 'ai_tool');
insert into item(name, category) values ('PPSPY', 'ai_tool');
insert into item(name, category) values ('Paragraph AI', 'ai_tool');
insert into item(name, category) values ('Parsio', 'ai_tool');
insert into item(name, category) values ('Photoshop Generative AI', 'ai_tool');
insert into item(name, category) values ('Photosonic', 'ai_tool');
insert into item(name, category) values ('Phrasly', 'ai_tool');
insert into item(name, category) values ('Picsart', 'ai_tool');
insert into item(name, category) values ('Pictory', 'ai_tool');
insert into item(name, category) values ('Pixlr', 'ai_tool');
insert into item(name, category) values ('Plagiashield', 'ai_tool');
insert into item(name, category) values ('Play.ht', 'ai_tool');
insert into item(name, category) values ('Playground AI', 'ai_tool');
insert into item(name, category) values ('PodStash', 'ai_tool');
insert into item(name, category) values ('Podcastle', 'ai_tool');
insert into item(name, category) values ('Podium', 'ai_tool');
insert into item(name, category) values ('Poised', 'ai_tool');
insert into item(name, category) values ('Postwise', 'ai_tool');
insert into item(name, category) values ('ProPhotos', 'ai_tool');
insert into item(name, category) values ('ProWritingAid', 'ai_tool');
insert into item(name, category) values ('Process AI', 'ai_tool');
insert into item(name, category) values ('Procys', 'ai_tool');
insert into item(name, category) values ('ProductScope', 'ai_tool');
insert into item(name, category) values ('Profile Pic Maker', 'ai_tool');
insert into item(name, category) values ('Profile Picture AI', 'ai_tool');
insert into item(name, category) values ('ProfilePro', 'ai_tool');
insert into item(name, category) values ('Prompt Hunt', 'ai_tool');
insert into item(name, category) values ('PromptLayer', 'ai_tool');
insert into item(name, category) values ('PromptPal', 'ai_tool');
insert into item(name, category) values ('Puppetry', 'ai_tool');
insert into item(name, category) values ('QR Galaxy', 'ai_tool');
insert into item(name, category) values ('Qodex', 'ai_tool');
insert into item(name, category) values ('Quickads', 'ai_tool');
insert into item(name, category) values ('Quillbot', 'ai_tool');
insert into item(name, category) values ('Quizgecko', 'ai_tool');
insert into item(name, category) values ('REimagineHome', 'ai_tool');
insert into item(name, category) values ('RankIQ', 'ai_tool');
insert into item(name, category) values ('RankPress', 'ai_tool');
insert into item(name, category) values ('Rask', 'ai_tool');
insert into item(name, category) values ('Recast', 'ai_tool');
insert into item(name, category) values ('Recast Studio', 'ai_tool');
insert into item(name, category) values ('Recut', 'ai_tool');
insert into item(name, category) values ('Reelio', 'ai_tool');
insert into item(name, category) values ('Referral Factory', 'ai_tool');
insert into item(name, category) values ('Reflect', 'ai_tool');
insert into item(name, category) values ('Remove BG', 'ai_tool');
insert into item(name, category) values ('RenderLion', 'ai_tool');
insert into item(name, category) values ('RepliQ', 'ai_tool');
insert into item(name, category) values ('Replit', 'ai_tool');
insert into item(name, category) values ('RepublicLabs', 'ai_tool');
insert into item(name, category) values ('Research Studio', 'ai_tool');
insert into item(name, category) values ('Riku', 'ai_tool');
insert into item(name, category) values ('Riverside Audio Transcription', 'ai_tool');
insert into item(name, category) values ('Runway ML', 'ai_tool');
insert into item(name, category) values ('Rytr', 'ai_tool');
insert into item(name, category) values ('SE Ranking', 'ai_tool');
insert into item(name, category) values ('SEO GPT', 'ai_tool');
insert into item(name, category) values ('SEOPress', 'ai_tool');
insert into item(name, category) values ('SEOmatic', 'ai_tool');
insert into item(name, category) values ('SUPERMACHINE', 'ai_tool');
insert into item(name, category) values ('Safuri', 'ai_tool');
insert into item(name, category) values ('Sanebox', 'ai_tool');
insert into item(name, category) values ('Scribe', 'ai_tool');
insert into item(name, category) values ('Secta Labs', 'ai_tool');
insert into item(name, category) values ('Semrush outline builder', 'ai_tool');
insert into item(name, category) values ('Sharp API', 'ai_tool');
insert into item(name, category) values ('Shortspilot', 'ai_tool');
insert into item(name, category) values ('Shuffll', 'ai_tool');
insert into item(name, category) values ('Simple Phones', 'ai_tool');
insert into item(name, category) values ('Simplified', 'ai_tool');
insert into item(name, category) values ('SiteSpeakAI', 'ai_tool');
insert into item(name, category) values ('Skybox Lab', 'ai_tool');
insert into item(name, category) values ('Snoooz', 'ai_tool');
insert into item(name, category) values ('SocialBee', 'ai_tool');
insert into item(name, category) values ('Softr AI', 'ai_tool');
insert into item(name, category) values ('SongR', 'ai_tool');
insert into item(name, category) values ('Sonic Link', 'ai_tool');
insert into item(name, category) values ('Soofy', 'ai_tool');
insert into item(name, category) values ('Soundraw', 'ai_tool');
insert into item(name, category) values ('Soundverse', 'ai_tool');
insert into item(name, category) values ('Speak AI', 'ai_tool');
insert into item(name, category) values ('Speechify', 'ai_tool');
insert into item(name, category) values ('Spikes Studio', 'ai_tool');
insert into item(name, category) values ('Squirrly SEO', 'ai_tool');
insert into item(name, category) values ('StealthGPT', 'ai_tool');
insert into item(name, category) values ('Steve AI', 'ai_tool');
insert into item(name, category) values ('StoryNest', 'ai_tool');
insert into item(name, category) values ('Submagic', 'ai_tool');
insert into item(name, category) values ('SudoWrite', 'ai_tool');
insert into item(name, category) values ('Super', 'ai_tool');
insert into item(name, category) values ('Surfer SEO', 'ai_tool');
insert into item(name, category) values ('Syllaby', 'ai_tool');
insert into item(name, category) values ('Synthesia', 'ai_tool');
insert into item(name, category) values ('Sysarchitect', 'ai_tool');
insert into item(name, category) values ('Tabnine', 'ai_tool');
insert into item(name, category) values ('Tailwind Ghostwriter', 'ai_tool');
insert into item(name, category) values ('TalkPal', 'ai_tool');
insert into item(name, category) values ('Talkio', 'ai_tool');
insert into item(name, category) values ('Taskade', 'ai_tool');
insert into item(name, category) values ('TeacherMatic', 'ai_tool');
insert into item(name, category) values ('TeamSmart AI', 'ai_tool');
insert into item(name, category) values ('Text Cortex', 'ai_tool');
insert into item(name, category) values ('Thoughtly', 'ai_tool');
insert into item(name, category) values ('TikTok', 'ai_tool');
insert into item(name, category) values ('Toasty AI', 'ai_tool');
insert into item(name, category) values ('Todoist AI Assistant', 'ai_tool');
insert into item(name, category) values ('Trinka AI', 'ai_tool');
insert into item(name, category) values ('Tripo AI', 'ai_tool');
insert into item(name, category) values ('TubeBuddy', 'ai_tool');
insert into item(name, category) values ('Tugan', 'ai_tool');
insert into item(name, category) values ('TurnCage', 'ai_tool');
insert into item(name, category) values ('Tweet Hunter', 'ai_tool');
insert into item(name, category) values ('TweetMonk', 'ai_tool');
insert into item(name, category) values ('Typefully', 'ai_tool');
insert into item(name, category) values ('Typeshare', 'ai_tool');
insert into item(name, category) values ('Typing Mind', 'ai_tool');
insert into item(name, category) values ('Upmetrics', 'ai_tool');
insert into item(name, category) values ('User Evaluation', 'ai_tool');
insert into item(name, category) values ('VEED', 'ai_tool');
insert into item(name, category) values ('Validly', 'ai_tool');
insert into item(name, category) values ('Vecteezy AI', 'ai_tool');
insert into item(name, category) values ('Vidalgo', 'ai_tool');
insert into item(name, category) values ('VideoGen', 'ai_tool');
insert into item(name, category) values ('VideoIdeas.ai', 'ai_tool');
insert into item(name, category) values ('Vidgen', 'ai_tool');
insert into item(name, category) values ('Vidnoz', 'ai_tool');
insert into item(name, category) values ('Viralkit', 'ai_tool');
insert into item(name, category) values ('Visily', 'ai_tool');
insert into item(name, category) values ('Visme AI', 'ai_tool');
insert into item(name, category) values ('Vista Social', 'ai_tool');
insert into item(name, category) values ('Voluum', 'ai_tool');
insert into item(name, category) values ('Wavel AI', 'ai_tool');
insert into item(name, category) values ('Waxwing', 'ai_tool');
insert into item(name, category) values ('WebWave', 'ai_tool');
insert into item(name, category) values ('WellSaid Labs', 'ai_tool');
insert into item(name, category) values ('WindsorAI', 'ai_tool');
insert into item(name, category) values ('Winston ai', 'ai_tool');
insert into item(name, category) values ('Wonderplan', 'ai_tool');
insert into item(name, category) values ('Wondershare Virbo', 'ai_tool');
insert into item(name, category) values ('Wondershare VirtuLook', 'ai_tool');
insert into item(name, category) values ('Writers brew', 'ai_tool');
insert into item(name, category) values ('Writesonic', 'ai_tool');
insert into item(name, category) values ('Yaara', 'ai_tool');
insert into item(name, category) values ('Yera', 'ai_tool');
insert into item(name, category) values ('grokai', 'ai_tool');
insert into item(name, category) values ('deepseek', 'ai_tool');
insert into item(name, category) values ('blackboxAI', 'ai_tool');
insert into item(name, category) values ('copyAI', 'ai_tool');
insert into item(name, category) values ('synthesia', 'ai_tool');
insert into item(name, category) values ('MidJourney', 'ai_tool');
insert into item(name, category) values ('Claude', 'ai_tool');
insert into item(name, category) values ('WordTune', 'ai_tool');
insert into item(name, category) values ('Runway', 'ai_tool');
insert into item(name, category) values ('YourMove AI', 'ai_tool');
insert into item(name, category) values ('Zentask', 'ai_tool');
insert into item(name, category) values ('Zigpoll', 'ai_tool');
insert into item(name, category) values ('Zyro', 'ai_tool');
insert into item(name, category) values ('aiApply', 'ai_tool');
insert into item(name, category) values ('aiCarousels', 'ai_tool');
insert into item(name, category) values ('guidde', 'ai_tool');
insert into item(name, category) values ('iApply', 'ai_tool');
insert into item(name, category) values ('iSpring Page', 'ai_tool');
insert into item(name, category) values ('n8n', 'ai_tool');
insert into item(name, category) values ('tinyEinstein', 'ai_tool');
insert into item(name, category) values ('tl;dv', 'ai_tool');
insert into item(name, category) values ('chatgpt43', 'ai_tool');
insert into item(name, category) values ('GROK', 'ai_tool');
insert into item(name, category) values ('SKYNET', 'ai_tool');
insert into item(name, category) values ('Midjourney', 'ai_tool');
insert into item(name, category) values ('Kling AI', 'ai_tool');
insert into item(name, category) values ('QUILTBOT', 'ai_tool');
insert into item(name, category) values ('QUILTBOT 2.0', 'ai_tool');
insert into item(name, category) values ('vnoyd', 'ai_tool');
insert into item(name, category) values ('chatgpt2', 'ai_tool');
insert into item(name, category) values ('chatgpt3', 'ai_tool');
insert into item(name, category) values ('notebooklm', 'ai_tool');
insert into item(name, category) values ('chatgpt13', 'ai_tool');
insert into item(name, category) values ('chatgpt16', 'ai_tool');
insert into item(name, category) values ('DALL.E', 'ai_tool');
insert into item(name, category) values ('GAMMA.AI', 'ai_tool');
insert into item(name, category) values ('chatgpt50', 'ai_tool');
insert into item(name, category) values ('perplexity', 'ai_tool');
insert into item(name, category) values ('chatgpt40', 'ai_tool');
insert into item(name, category) values ('Jasper Ai', 'ai_tool');
insert into item(name, category) values ('AgentGPT', 'ai_tool');
insert into item(name, category) values ('cluade', 'ai_tool');
insert into item(name, category) values ('AI Dating', 'ai_tool');
insert into item(name, category) values ('Leonardo', 'ai_tool');
insert into item(name, category) values ('Gemini', 'ai_tool');
insert into item(name, category) values ('Pika Labs', 'ai_tool');
insert into item(name, category) values ('Boomy', 'ai_tool');
insert into item(name, category) values ('stealth writer', 'ai_tool');
insert into item(name, category) values ('Copilot', 'ai_tool');
insert into item(name, category) values ('FATHOM', 'ai_tool');
insert into item(name, category) values ('AIVA', 'ai_tool');
