insert into item(name, category) values ('Gemischtes Hack', 'podcast');
insert into item(name, category) values ('Mordlust', 'podcast');
insert into item(name, category) values ('Kaulitz Hills - Senf aus Hollywood', 'podcast');
insert into item(name, category) values ('Fest & Flauschig', 'podcast');
insert into item(name, category) values ('MORD AUF EX', 'podcast');
insert into item(name, category) values ('LANZ & PRECHT', 'podcast');
insert into item(name, category) values ('Baywatch Berlin', 'podcast');
insert into item(name, category) values ('Offline + Ehrlich', 'podcast');
insert into item(name, category) values ('Verbrechen', 'podcast');
insert into item(name, category) values ('Dick & Doof', 'podcast');
insert into item(name, category) values ('Hobbylos', 'podcast');
insert into item(name, category) values ('Edeltalk - mit Dominik & Kevin', 'podcast');
insert into item(name, category) values ('Lewinray ', 'podcast');
insert into item(name, category) values ('Wissen Weekly', 'podcast');
insert into item(name, category) values ('Die Nervigen', 'podcast');
insert into item(name, category) values ('Copa TS', 'podcast');
insert into item(name, category) values ('Aktenzeichen XY… Unvergessene Verbrechen', 'podcast');
insert into item(name, category) values ('Simplicissimus', 'podcast');
insert into item(name, category) values ('Henke''s Corner', 'podcast');
insert into item(name, category) values ('Clare on Air', 'podcast');
insert into item(name, category) values ('Lage der Nation - der Politik-Podcast aus Berlin', 'podcast');
insert into item(name, category) values ('Hotel Matze', 'podcast');
insert into item(name, category) values ('Was jetzt?', 'podcast');
insert into item(name, category) values ('RONZHEIMER.', 'podcast');
insert into item(name, category) values ('Verbrechen von nebenan: True Crime aus der Nachbarschaft', 'podcast');
insert into item(name, category) values ('Apokalypse & Filterkaffee', 'podcast');
insert into item(name, category) values ('Hoss & Hopf', 'podcast');
insert into item(name, category) values ('UNFASSBAR – ein Simplicissimus Podcast', 'podcast');
insert into item(name, category) values ('Die Nachrichten', 'podcast');
insert into item(name, category) values ('Tim Gabel Podcast', 'podcast');
insert into item(name, category) values ('Talk ohne Gast', 'podcast');
insert into item(name, category) values ('Zum Scheitern Verurteilt', 'podcast');
insert into item(name, category) values ('Kaffee mit Zitrone ', 'podcast');
insert into item(name, category) values ('Kurt Krömer - Feelings', 'podcast');
insert into item(name, category) values ('Wissen mit Johnny', 'podcast');
insert into item(name, category) values ('Mord am Mittwoch - True Crime', 'podcast');
insert into item(name, category) values ('Keine Echten Männer', 'podcast');
insert into item(name, category) values ('laserluca', 'podcast');
insert into item(name, category) values ('Auf den Punkt', 'podcast');
insert into item(name, category) values ('Serienkiller - Mörder und ihre Geschichten', 'podcast');
insert into item(name, category) values ('ViscaTabak - Der Fußball Podcast', 'podcast');
insert into item(name, category) values ('Handelsblatt Morning Briefing - News aus Wirtschaft, Politik und Finanzen', 'podcast');
insert into item(name, category) values ('G Spot mit Stefanie Giesinger', 'podcast');
insert into item(name, category) values ('PLOT HOUSE', 'podcast');
insert into item(name, category) values ('Bayern 3 True Crime - Schuld und Unschuld', 'podcast');
insert into item(name, category) values ('Geschichten aus der Geschichte', 'podcast');
insert into item(name, category) values ('ARD Crime Time – Der True Crime Podcast', 'podcast');
insert into item(name, category) values ('DRINNIES', 'podcast');
insert into item(name, category) values ('Der Sophie Passmann Podcast', 'podcast');
insert into item(name, category) values ('Freundschaft Minus', 'podcast');
insert into item(name, category) values ('Das Politikteil', 'podcast');
insert into item(name, category) values ('Machtwechsel – mit Dagmar Rosenfeld und Robin Alexander', 'podcast');
insert into item(name, category) values ('50+2 - Der Fussballpodcast mit Nico & Niklas', 'podcast');
insert into item(name, category) values ('15 Minuten. Der tagesschau-Podcast am Morgen', 'podcast');
insert into item(name, category) values ('Rick Azas', 'podcast');
insert into item(name, category) values ('Benx', 'podcast');
insert into item(name, category) values ('El Margo', 'podcast');
insert into item(name, category) values ('Bratwurst und Baklava - mit Özcan Cosar und Bastian Bielendorfer', 'podcast');
insert into item(name, category) values ('Das Wissen | SWR', 'podcast');
insert into item(name, category) values ('Zwei Vermengte', 'podcast');
insert into item(name, category) values ('tagesschau in 100 Sekunden (Audio-Podcast)', 'podcast');
insert into item(name, category) values ('Alles gesagt?', 'podcast');
insert into item(name, category) values ('Girls Girls ', 'podcast');
insert into item(name, category) values ('{ungeskriptet} - Gespräche, die dich weiter bringen', 'podcast');
insert into item(name, category) values ('0630 - der News-Podcast', 'podcast');
insert into item(name, category) values ('Politik mit Anne Will', 'podcast');
insert into item(name, category) values ('OK, America?', 'podcast');
insert into item(name, category) values ('Die Deutschen Podcast', 'podcast');
insert into item(name, category) values ('So bin ich eben! Stefanie Stahls Psychologie-Podcast für alle "Normalgestörten"', 'podcast');
insert into item(name, category) values ('Reeze', 'podcast');
insert into item(name, category) values ('Schwarze Akte - True Crime', 'podcast');
insert into item(name, category) values ('Psychologie to go!', 'podcast');
insert into item(name, category) values ('Ziemlich beste Fremde', 'podcast');
insert into item(name, category) values ('Mit den Waffeln einer Frau', 'podcast');
insert into item(name, category) values ('Der Tag', 'podcast');
insert into item(name, category) values ('Alles auf Aktien – Die täglichen Finanzen-News', 'podcast');
insert into item(name, category) values ('too many tabs – der Podcast', 'podcast');
insert into item(name, category) values ('11KM: der tagesschau-Podcast', 'podcast');
insert into item(name, category) values ('Betreutes Fühlen', 'podcast');
insert into item(name, category) values ('Eine Stunde History - Deutschlandfunk Nova', 'podcast');
insert into item(name, category) values ('Was bisher geschah - Geschichtspodcast', 'podcast');
insert into item(name, category) values ('Einfach mal Luppen', 'podcast');
insert into item(name, category) values ('Kalk & Welk - Die fabelhaften Boomer Boys', 'podcast');
insert into item(name, category) values ('Äffchen mit Käffchen', 'podcast');
insert into item(name, category) values ('Hazel Thomas Hörerlebnis', 'podcast');
insert into item(name, category) values ('CheckPod - Der Podcast mit Checker Tobi', 'podcast');
insert into item(name, category) values ('Quarks Daily', 'podcast');
insert into item(name, category) values ('TRUE LOVE', 'podcast');
insert into item(name, category) values ('OMR Podcast', 'podcast');
insert into item(name, category) values ('FOOTBALL BROMANCE', 'podcast');
insert into item(name, category) values ('Quarks Science Cops', 'podcast');
insert into item(name, category) values ('tagesschau (Audio-Podcast)', 'podcast');
insert into item(name, category) values ('Acht Milliarden - Der Auslandspodcast des SPIEGEL', 'podcast');
insert into item(name, category) values ('Im Visier – Verbrecherjagd in Berlin und Brandenburg', 'podcast');
insert into item(name, category) values ('Eyes in the Dark', 'podcast');
insert into item(name, category) values ('Gysi gegen Guttenberg – Der Deutschland Podcast', 'podcast');
insert into item(name, category) values ('BLIND DATING 💔 mit Ceddo', 'podcast');
insert into item(name, category) values ('Skandal, Skandal', 'podcast');
insert into item(name, category) values ('life is felicious', 'podcast');
insert into item(name, category) values ('Darwin gefällt das', 'podcast');
insert into item(name, category) values ('Julia Leischik: Spurlos', 'podcast');
insert into item(name, category) values ('tomatolix', 'podcast');
insert into item(name, category) values ('F.A.Z. Frühdenker - Die Nachrichten am Morgen', 'podcast');
insert into item(name, category) values ('The Joe Rogan Experience', 'podcast');
insert into item(name, category) values ('Paarspektiven', 'podcast');
insert into item(name, category) values ('Jung & Naiv', 'podcast');
insert into item(name, category) values ('5 Minuten Harry Podcast von Coldmirror', 'podcast');
insert into item(name, category) values ('Stahl aber herzlich – Der Psychotherapie-Podcast mit Stefanie Stahl', 'podcast');
insert into item(name, category) values ('Ohne Bewährung - True Crime von hier', 'podcast');
insert into item(name, category) values ('stern Crime - Spurensuche', 'podcast');
insert into item(name, category) values ('The Pioneer Briefing', 'podcast');
insert into item(name, category) values ('Gnu', 'podcast');
insert into item(name, category) values ('Papaplatte', 'podcast');
insert into item(name, category) values ('Niemand muss ein Promi sein - Deutschlands Nr. 1 Gossip-Podcast!', 'podcast');
insert into item(name, category) values ('Table Today', 'podcast');
insert into item(name, category) values ('Gefühlte Fakten', 'podcast');
insert into item(name, category) values ('EinfachGustaf | Dein Minecraft Kanal!', 'podcast');
insert into item(name, category) values ('Alex Freerun', 'podcast');
insert into item(name, category) values ('Raum & Zeit', 'podcast');
insert into item(name, category) values ('dudes.', 'podcast');
insert into item(name, category) values ('Geld für die Welt', 'podcast');
insert into item(name, category) values ('happy, holy & confident® Dein Podcast fürs Herz und den Verstand', 'podcast');
insert into item(name, category) values ('Kampf der Unternehmen', 'podcast');
insert into item(name, category) values ('F.A.Z. Podcast für Deutschland', 'podcast');
insert into item(name, category) values ('Aha! Zehn Minuten Alltags-Wissen', 'podcast');
insert into item(name, category) values ('Feel The News', 'podcast');
insert into item(name, category) values ('Handelsblatt Today - Der Finanzpodcast mit News zu Börse, Aktien und Geldanlage', 'podcast');
insert into item(name, category) values ('FUSSBALL MML', 'podcast');
insert into item(name, category) values ('Johannesmlz', 'podcast');
insert into item(name, category) values ('Ehrenwort - Ein Podcast über Skandale', 'podcast');
insert into item(name, category) values ('Verbrechen der Vergangenheit', 'podcast');
insert into item(name, category) values ('Zeigler & Köster - Der Fußball-Podcast von 11FREUNDE', 'podcast');
insert into item(name, category) values ('Streitkräfte und Strategien', 'podcast');
insert into item(name, category) values ('DAS PODCAST UFO', 'podcast');
insert into item(name, category) values ('Nie & Immer', 'podcast');
insert into item(name, category) values ('CALCIO BERLIN', 'podcast');
insert into item(name, category) values ('Mensch! Promi Skandale und ihre Geschichte', 'podcast');
insert into item(name, category) values ('Reif ist live – Fußball Talk von BILD', 'podcast');
insert into item(name, category) values ('Besser als Sex', 'podcast');
insert into item(name, category) values ('Firewall: Jedes System hat eine Schwachstelle', 'podcast');
insert into item(name, category) values ('Beste Freundinnen', 'podcast');
insert into item(name, category) values ('Dieser eine Moment – Der Podcast mit Philipp Fleiter', 'podcast');
insert into item(name, category) values ('Youtify', 'podcast');
insert into item(name, category) values ('POLITICO Berlin Playbook', 'podcast');
insert into item(name, category) values ('Pferdeschwänze', 'podcast');
insert into item(name, category) values ('Nachmittagsjause mit Ankat', 'podcast');
insert into item(name, category) values ('Wahre Verbrechen - True Crime Podcast', 'podcast');
insert into item(name, category) values ('OHNE AKTIEN WIRD SCHWER - Tägliche Börsen-News', 'podcast');
insert into item(name, category) values ('Der Politikpodcast', 'podcast');
insert into item(name, category) values ('Was die Woche wichtig war – Der funk-Podcast', 'podcast');
insert into item(name, category) values ('PietCast', 'podcast');
insert into item(name, category) values ('Dark Matters – Geheimnisse der Geheimdienste', 'podcast');
insert into item(name, category) values ('Alliteration Am Arsch', 'podcast');
insert into item(name, category) values ('Sternstunde Philosophie', 'podcast');
insert into item(name, category) values ('Tatort Deutschland – Wahre Kriminalfälle und Verbrechen', 'podcast');
insert into item(name, category) values ('Weird Crimes', 'podcast');
insert into item(name, category) values ('Die Lage', 'podcast');
insert into item(name, category) values ('Im Bett mit Anna-Maria und Anis Ferchichi - Der Bushido Podcast', 'podcast');
insert into item(name, category) values ('Brawler''s World', 'podcast');
insert into item(name, category) values ('Jay & Arya - Der eigentlich ganz gute Podcast', 'podcast');
insert into item(name, category) values ('Adoptivbrüder – mit Hannes & Jeremy', 'podcast');
insert into item(name, category) values ('Das wahre Leben – Der NACHTCAFÉ Podcast', 'podcast');
insert into item(name, category) values ('Puppies and Crime', 'podcast');
insert into item(name, category) values ('The Diary Of A CEO with Steven Bartlett', 'podcast');
insert into item(name, category) values ('Wie geht''s? mit Robin Gosens', 'podcast');
insert into item(name, category) values ('Terra X History - Der Podcast', 'podcast');
insert into item(name, category) values ('Macht und Millionen – Der Podcast über echte Wirtschaftskrimis', 'podcast');
insert into item(name, category) values ('Deutschland3000 - ''ne gute Stunde mit Eva Schulz', 'podcast');
insert into item(name, category) values ('Lästerschwestern', 'podcast');
insert into item(name, category) values ('Was tun, Herr General? - Der Podcast zum Ukraine-Krieg', 'podcast');
insert into item(name, category) values ('CRIME TIME', 'podcast');
insert into item(name, category) values ('Finanzfluss Podcast', 'podcast');
insert into item(name, category) values ('Paula Lieben Lernen', 'podcast');
insert into item(name, category) values ('Stammplatz – Fußball News täglich', 'podcast');
insert into item(name, category) values ('Phrasenmäher - Fußball Talk mit Henning Feindt und André Albers', 'podcast');
insert into item(name, category) values ('Haschimitenfürst – Der Bobcast', 'podcast');
insert into item(name, category) values ('Ulle & Rick', 'podcast');
insert into item(name, category) values ('Theresa Kirchner', 'podcast');
insert into item(name, category) values ('Sekten & Kulte - Im Namen des Bösen', 'podcast');
insert into item(name, category) values ('Insolito - Nur ein weiterer TrueCrime-Podcast', 'podcast');
insert into item(name, category) values ('Weltspiegel Podcast', 'podcast');
insert into item(name, category) values ('THE BIG HEAD JUAN SHOW (NSFW)', 'podcast');
insert into item(name, category) values ('Einschlafen mit Hogwarts', 'podcast');
insert into item(name, category) values ('Stimmen im Kopf - True-Crime / Mystery Podcast', 'podcast');
insert into item(name, category) values ('Down Set Talk! - Der NFL Podcast von RTL', 'podcast');
insert into item(name, category) values ('His2Go - Geschichte Podcast', 'podcast');
insert into item(name, category) values ('Die Drei Rabauken', 'podcast');
insert into item(name, category) values ('Augstein & Blome', 'podcast');
insert into item(name, category) values ('maischberger. der podcast', 'podcast');
insert into item(name, category) values ('Dings und Bums', 'podcast');
insert into item(name, category) values ('Alle meine Eltern – Der Real Talk mit Evelyn Weigert', 'podcast');
insert into item(name, category) values ('Handelsblatt Crime - spannende Streitfälle der deutschen Wirtschaft', 'podcast');
insert into item(name, category) values ('Spitzengespräch', 'podcast');
insert into item(name, category) values ('MutterSöhnchen', 'podcast');
insert into item(name, category) values ('Einschlafen mit Wikipedia', 'podcast');
insert into item(name, category) values ('Science Crimes', 'podcast');
insert into item(name, category) values ('Make Economy Great Again', 'podcast');
insert into item(name, category) values ('Alman Arabica', 'podcast');
insert into item(name, category) values ('Sicherheitshalber', 'podcast');
insert into item(name, category) values ('ZEIT WISSEN. Woher weißt Du das?', 'podcast');
