create table app_user(username text primary key, password_bcrypt_hash text not null);

create table item(name text, category text, primary key (name, category));

create table feature(name text primary key);

create table item_feature(
    item_name text,
    item_category text,
    foreign key (item_name, item_category) references item on delete cascade on update cascade,

    feature text references feature(name),

    primary key (item_name, item_category, feature)
);

create table review(
    username text references app_user on delete cascade on update cascade,
    item_name text,
    item_category text,
    rating int not null check (rating >= 0 and rating <= 10),
    foreign key (item_name, item_category) references item on delete cascade on update cascade,
    primary key (username, item_name, item_category)
);

create materialized view pearson as (
    with common_ratings as (
        select
            r1.item_name,
            r1.item_category,
            r1.username as ua,
            r1.rating as ra,
            r2.username as ub,
            r2.rating as rb
        from review as r1
        join review as r2
            on r1.item_name = r2.item_name and r1.item_category = r2.item_category
            and r1.username < r2.username
    ),
    average_ratings as (
        select
            username,
            avg(rating) as avg_rating
        from review
        group by username
    )
    select
        ua,
        ub,
        sum((ra - aa.avg_rating) * (rb - ab.avg_rating))
            / (sqrt(sum((ra - aa.avg_rating)^2)) * sqrt(sum((rb - ab.avg_rating)^2))) as similarity
    from common_ratings
        join lateral 
            (select avg_rating from average_ratings where username = ua) as aa
            on true
        join lateral
            (select avg_rating from average_ratings where username = ub) as ab
            on true
    group by ua, ub
);

insert into item(name, category) values ('chatgpt5', 'ai_tool');
insert into item(name, category) values ('NOTION AI', 'ai_tool');
insert into item(name, category) values ('BIXBY', 'ai_tool');
insert into item(name, category) values ('GEMINI', 'ai_tool');
insert into item(name, category) values ('chatgpt', 'ai_tool');
insert into item(name, category) values ('Grammarly', 'ai_tool');
insert into item(name, category) values ('AITable', 'ai_tool');
insert into item(name, category) values ('10Web', 'ai_tool');
insert into item(name, category) values ('AI Detector Pro', 'ai_tool');
insert into item(name, category) values ('AI Lawyer', 'ai_tool');
insert into item(name, category) values ('AI Room Planner', 'ai_tool');
insert into item(name, category) values ('AI Voice Detector', 'ai_tool');
insert into item(name, category) values ('AIPRM', 'ai_tool');
insert into item(name, category) values ('AISEO', 'ai_tool');
insert into item(name, category) values ('AISEO Art', 'ai_tool');
insert into item(name, category) values ('AdCreative.ai', 'ai_tool');
insert into item(name, category) values ('Adalo', 'ai_tool');
insert into item(name, category) values ('Adobe Express', 'ai_tool');
insert into item(name, category) values ('Adobe Firefly', 'ai_tool');
insert into item(name, category) values ('Adobe Podcast', 'ai_tool');
insert into item(name, category) values ('Adobe Sensei', 'ai_tool');
insert into item(name, category) values ('AimReply', 'ai_tool');
insert into item(name, category) values ('Alphana', 'ai_tool');
insert into item(name, category) values ('Altered', 'ai_tool');
insert into item(name, category) values ('AnimeGenius', 'ai_tool');
insert into item(name, category) values ('Apify', 'ai_tool');
insert into item(name, category) values ('Aragon', 'ai_tool');
insert into item(name, category) values ('Artflow', 'ai_tool');
insert into item(name, category) values ('Artsmart AI', 'ai_tool');
insert into item(name, category) values ('Audio writer', 'ai_tool');
insert into item(name, category) values ('Audo', 'ai_tool');
insert into item(name, category) values ('Aura AI', 'ai_tool');
insert into item(name, category) values ('AutoShorts', 'ai_tool');
insert into item(name, category) values ('Automata', 'ai_tool');
insert into item(name, category) values ('Bannerbear', 'ai_tool');
insert into item(name, category) values ('BatchTable', 'ai_tool');
insert into item(name, category) values ('BeforeSunset AI', 'ai_tool');
insert into item(name, category) values ('Bertha AI', 'ai_tool');
insert into item(name, category) values ('BetterPic', 'ai_tool');
insert into item(name, category) values ('Biread', 'ai_tool');
insert into item(name, category) values ('Bizway', 'ai_tool');
insert into item(name, category) values ('Black Friday Deals', 'ai_tool');
insert into item(name, category) values ('Blaze', 'ai_tool');
insert into item(name, category) values ('Bodt', 'ai_tool');
insert into item(name, category) values ('Brain FM', 'ai_tool');
insert into item(name, category) values ('Brand24', 'ai_tool');
insert into item(name, category) values ('Browse AI', 'ai_tool');
insert into item(name, category) values ('Bubble AI', 'ai_tool');
insert into item(name, category) values ('Caspar AI', 'ai_tool');
insert into item(name, category) values ('Castmagic', 'ai_tool');
insert into item(name, category) values ('Catbird', 'ai_tool');
insert into item(name, category) values ('Chaindesk', 'ai_tool');
insert into item(name, category) values ('Chance AI', 'ai_tool');
insert into item(name, category) values ('Character AI', 'ai_tool');
insert into item(name, category) values ('ChatGPT', 'ai_tool');
insert into item(name, category) values ('ChatGPT Writer', 'ai_tool');
insert into item(name, category) values ('ChatPlayground', 'ai_tool');
insert into item(name, category) values ('Cheatlayer', 'ai_tool');
insert into item(name, category) values ('Chivvy', 'ai_tool');
insert into item(name, category) values ('Cleanvoice', 'ai_tool');
insert into item(name, category) values ('Clickup', 'ai_tool');
insert into item(name, category) values ('ClipBuddy', 'ai_tool');
insert into item(name, category) values ('Cliptalk', 'ai_tool');
insert into item(name, category) values ('Clockk', 'ai_tool');
insert into item(name, category) values ('CoachVox', 'ai_tool');
insert into item(name, category) values ('Coda AI', 'ai_tool');
insert into item(name, category) values ('CodeDesign', 'ai_tool');
insert into item(name, category) values ('Codeleaks', 'ai_tool');
insert into item(name, category) values ('CodiumAI', 'ai_tool');
insert into item(name, category) values ('Compose AI', 'ai_tool');
insert into item(name, category) values ('ContentBot', 'ai_tool');
insert into item(name, category) values ('ContentShake', 'ai_tool');
insert into item(name, category) values ('ContentStudio AI', 'ai_tool');
insert into item(name, category) values ('CopySpace', 'ai_tool');
insert into item(name, category) values ('CourseAI', 'ai_tool');
insert into item(name, category) values ('Coursebox AI', 'ai_tool');
insert into item(name, category) values ('Craiyon', 'ai_tool');
insert into item(name, category) values ('Creaitor', 'ai_tool');
insert into item(name, category) values ('Creatify', 'ai_tool');
insert into item(name, category) values ('Creatr', 'ai_tool');
insert into item(name, category) values ('Cuppa', 'ai_tool');
insert into item(name, category) values ('CustomGPT', 'ai_tool');
insert into item(name, category) values ('DET Practice', 'ai_tool');
insert into item(name, category) values ('Dante', 'ai_tool');
insert into item(name, category) values ('Dashworks', 'ai_tool');
insert into item(name, category) values ('Deblank', 'ai_tool');
insert into item(name, category) values ('Deciphr', 'ai_tool');
insert into item(name, category) values ('Decktopus', 'ai_tool');
insert into item(name, category) values ('DeepBrain', 'ai_tool');
insert into item(name, category) values ('DeepL', 'ai_tool');
insert into item(name, category) values ('Describely', 'ai_tool');
insert into item(name, category) values ('Descript', 'ai_tool');
insert into item(name, category) values ('DescriptionWise', 'ai_tool');
insert into item(name, category) values ('Devi AI', 'ai_tool');
insert into item(name, category) values ('DigitalFirst', 'ai_tool');
insert into item(name, category) values ('DimeADozen', 'ai_tool');
insert into item(name, category) values ('Divi AI', 'ai_tool');
insert into item(name, category) values ('Durable', 'ai_tool');
insert into item(name, category) values ('Dzine', 'ai_tool');
insert into item(name, category) values ('Eagle', 'ai_tool');
insert into item(name, category) values ('Easy Peasy', 'ai_tool');
insert into item(name, category) values ('Eclipse AI', 'ai_tool');
insert into item(name, category) values ('Ecommerce Prompts', 'ai_tool');
insert into item(name, category) values ('Elai', 'ai_tool');
insert into item(name, category) values ('Elementor AI', 'ai_tool');
insert into item(name, category) values ('Elephas', 'ai_tool');
insert into item(name, category) values ('ElevenLabs', 'ai_tool');
insert into item(name, category) values ('Eloise AI', 'ai_tool');
insert into item(name, category) values ('Email Magic', 'ai_tool');
insert into item(name, category) values ('Endless VN', 'ai_tool');
insert into item(name, category) values ('Exolyt', 'ai_tool');
insert into item(name, category) values ('FYLM.ai', 'ai_tool');
insert into item(name, category) values ('Fathom', 'ai_tool');
insert into item(name, category) values ('Feathery', 'ai_tool');
insert into item(name, category) values ('Fellow', 'ai_tool');
insert into item(name, category) values ('Filmora', 'ai_tool');
insert into item(name, category) values ('Fireflies', 'ai_tool');
insert into item(name, category) values ('Flowrite', 'ai_tool');
insert into item(name, category) values ('Followr', 'ai_tool');
insert into item(name, category) values ('Formula Bot', 'ai_tool');
insert into item(name, category) values ('Frame', 'ai_tool');
insert into item(name, category) values ('Framer', 'ai_tool');
insert into item(name, category) values ('Frase', 'ai_tool');
insert into item(name, category) values ('Freeflo', 'ai_tool');
insert into item(name, category) values ('Future Desk', 'ai_tool');
insert into item(name, category) values ('GPT zero', 'ai_tool');
insert into item(name, category) values ('GPTinf', 'ai_tool');
insert into item(name, category) values ('GPTkit', 'ai_tool');
insert into item(name, category) values ('Galaxy AI', 'ai_tool');
insert into item(name, category) values ('GetGenie', 'ai_tool');
insert into item(name, category) values ('GetResponse', 'ai_tool');
insert into item(name, category) values ('Ghost Writer', 'ai_tool');
insert into item(name, category) values ('GhostContent', 'ai_tool');
insert into item(name, category) values ('Github Autopilot', 'ai_tool');
insert into item(name, category) values ('Glasp', 'ai_tool');
insert into item(name, category) values ('Gling', 'ai_tool');
insert into item(name, category) values ('GoCharlie', 'ai_tool');
insert into item(name, category) values ('Google Workspace', 'ai_tool');
insert into item(name, category) values ('Guidejar', 'ai_tool');
insert into item(name, category) values ('Gummysearch', 'ai_tool');
insert into item(name, category) values ('HEIGHTS AI', 'ai_tool');
insert into item(name, category) values ('HIX Bypass', 'ai_tool');
insert into item(name, category) values ('Hansei', 'ai_tool');
insert into item(name, category) values ('Harpa AI', 'ai_tool');
insert into item(name, category) values ('HeadshotPro', 'ai_tool');
insert into item(name, category) values ('Hexofy', 'ai_tool');
insert into item(name, category) values ('Hexomatic', 'ai_tool');
insert into item(name, category) values ('Hexometer', 'ai_tool');
insert into item(name, category) values ('Hexowatch', 'ai_tool');
insert into item(name, category) values ('HeyGen', 'ai_tool');
insert into item(name, category) values ('Hify', 'ai_tool');
insert into item(name, category) values ('Hiver', 'ai_tool');
insert into item(name, category) values ('HookSounds AI Studio', 'ai_tool');
insert into item(name, category) values ('HoppyCopy', 'ai_tool');
insert into item(name, category) values ('Hotpot', 'ai_tool');
insert into item(name, category) values ('Hotreach AI', 'ai_tool');
insert into item(name, category) values ('Hubspot AI', 'ai_tool');
insert into item(name, category) values ('HypeAuditor', 'ai_tool');
insert into item(name, category) values ('HypeFury', 'ai_tool');
insert into item(name, category) values ('Hypernatural', 'ai_tool');
insert into item(name, category) values ('IMAI', 'ai_tool');
insert into item(name, category) values ('Icon', 'ai_tool');
insert into item(name, category) values ('InLinks', 'ai_tool');
insert into item(name, category) values ('InsightBaseAI', 'ai_tool');
insert into item(name, category) values ('InterviewSpark', 'ai_tool');
insert into item(name, category) values ('Inworld', 'ai_tool');
insert into item(name, category) values ('Jasper', 'ai_tool');
insert into item(name, category) values ('JoggAI', 'ai_tool');
insert into item(name, category) values ('Jupitrr', 'ai_tool');
insert into item(name, category) values ('KIVA', 'ai_tool');
insert into item(name, category) values ('Kafkai', 'ai_tool');
insert into item(name, category) values ('Katteb', 'ai_tool');
insert into item(name, category) values ('Keyword Insights', 'ai_tool');
insert into item(name, category) values ('KeywordsPeopleUse', 'ai_tool');
insert into item(name, category) values ('Klap', 'ai_tool');
insert into item(name, category) values ('Koala AI', 'ai_tool');
insert into item(name, category) values ('Kudra', 'ai_tool');
insert into item(name, category) values ('Lalal AI', 'ai_tool');
insert into item(name, category) values ('Landr', 'ai_tool');
insert into item(name, category) values ('Lately', 'ai_tool');
insert into item(name, category) values ('Leadpages AI Engine', 'ai_tool');
insert into item(name, category) values ('LearnWorlds AI', 'ai_tool');
insert into item(name, category) values ('LensGo', 'ai_tool');
insert into item(name, category) values ('Letterdrop', 'ai_tool');
insert into item(name, category) values ('Letterly', 'ai_tool');
insert into item(name, category) values ('Lexica', 'ai_tool');
insert into item(name, category) values ('Liner', 'ai_tool');
insert into item(name, category) values ('Linguix', 'ai_tool');
insert into item(name, category) values ('Link Whisper AI', 'ai_tool');
insert into item(name, category) values ('LogicLister', 'ai_tool');
insert into item(name, category) values ('Logo AI', 'ai_tool');
insert into item(name, category) values ('Looka', 'ai_tool');
insert into item(name, category) values ('Lovable', 'ai_tool');
insert into item(name, category) values ('Lovo', 'ai_tool');
insert into item(name, category) values ('Luma AI', 'ai_tool');
insert into item(name, category) values ('Luna', 'ai_tool');
insert into item(name, category) values ('Luna AI', 'ai_tool');
insert into item(name, category) values ('Lunacy by Icons8', 'ai_tool');
insert into item(name, category) values ('Lyro by Tidio', 'ai_tool');
insert into item(name, category) values ('Magai', 'ai_tool');
insert into item(name, category) values ('Magic Hour', 'ai_tool');
insert into item(name, category) values ('Magic Studio', 'ai_tool');
insert into item(name, category) values ('MagicReply', 'ai_tool');
insert into item(name, category) values ('Make', 'ai_tool');
insert into item(name, category) values ('Manatal', 'ai_tool');
insert into item(name, category) values ('Marketing Megaprompts', 'ai_tool');
insert into item(name, category) values ('Marketmuse', 'ai_tool');
insert into item(name, category) values ('Media.io', 'ai_tool');
insert into item(name, category) values ('Merlin', 'ai_tool');
insert into item(name, category) values ('MicMonster', 'ai_tool');
insert into item(name, category) values ('Midjourney Prompt Generator', 'ai_tool');
insert into item(name, category) values ('MimicPC', 'ai_tool');
insert into item(name, category) values ('MindPal', 'ai_tool');
insert into item(name, category) values ('Mixo', 'ai_tool');
insert into item(name, category) values ('Monic AI', 'ai_tool');
insert into item(name, category) values ('Monica', 'ai_tool');
insert into item(name, category) values ('Monkeebrain', 'ai_tool');
insert into item(name, category) values ('Moonbeam', 'ai_tool');
insert into item(name, category) values ('MosaChat-AI', 'ai_tool');
insert into item(name, category) values ('Motiva', 'ai_tool');
insert into item(name, category) values ('Mubert', 'ai_tool');
insert into item(name, category) values ('Munch', 'ai_tool');
insert into item(name, category) values ('Murf', 'ai_tool');
insert into item(name, category) values ('My GPT Wizard', 'ai_tool');
insert into item(name, category) values ('Nanonets', 'ai_tool');
insert into item(name, category) values ('Nara', 'ai_tool');
insert into item(name, category) values ('Nekton AI', 'ai_tool');
insert into item(name, category) values ('Netus AI', 'ai_tool');
insert into item(name, category) values ('Neural Love', 'ai_tool');
insert into item(name, category) values ('NeuralNewsletters', 'ai_tool');
insert into item(name, category) values ('Neuraltext', 'ai_tool');
insert into item(name, category) values ('Notion AI', 'ai_tool');
insert into item(name, category) values ('NovelAI', 'ai_tool');
insert into item(name, category) values ('Numerous AI', 'ai_tool');
insert into item(name, category) values ('Olympia', 'ai_tool');
insert into item(name, category) values ('One Click Human', 'ai_tool');
insert into item(name, category) values ('OpusClip', 'ai_tool');
insert into item(name, category) values ('Originality AI', 'ai_tool');
insert into item(name, category) values ('OutGrow', 'ai_tool');
insert into item(name, category) values ('PDF Flex', 'ai_tool');
insert into item(name, category) values ('PDF ai', 'ai_tool');
insert into item(name, category) values ('PPSPY', 'ai_tool');
insert into item(name, category) values ('Paragraph AI', 'ai_tool');
insert into item(name, category) values ('Parsio', 'ai_tool');
insert into item(name, category) values ('Photoshop Generative AI', 'ai_tool');
insert into item(name, category) values ('Photosonic', 'ai_tool');
insert into item(name, category) values ('Phrasly', 'ai_tool');
insert into item(name, category) values ('Picsart', 'ai_tool');
insert into item(name, category) values ('Pictory', 'ai_tool');
insert into item(name, category) values ('Pixlr', 'ai_tool');
insert into item(name, category) values ('Plagiashield', 'ai_tool');
insert into item(name, category) values ('Play.ht', 'ai_tool');
insert into item(name, category) values ('Playground AI', 'ai_tool');
insert into item(name, category) values ('PodStash', 'ai_tool');
insert into item(name, category) values ('Podcastle', 'ai_tool');
insert into item(name, category) values ('Podium', 'ai_tool');
insert into item(name, category) values ('Poised', 'ai_tool');
insert into item(name, category) values ('Postwise', 'ai_tool');
insert into item(name, category) values ('ProPhotos', 'ai_tool');
insert into item(name, category) values ('ProWritingAid', 'ai_tool');
insert into item(name, category) values ('Process AI', 'ai_tool');
insert into item(name, category) values ('Procys', 'ai_tool');
insert into item(name, category) values ('ProductScope', 'ai_tool');
insert into item(name, category) values ('Profile Pic Maker', 'ai_tool');
insert into item(name, category) values ('Profile Picture AI', 'ai_tool');
insert into item(name, category) values ('ProfilePro', 'ai_tool');
insert into item(name, category) values ('Prompt Hunt', 'ai_tool');
insert into item(name, category) values ('PromptLayer', 'ai_tool');
insert into item(name, category) values ('PromptPal', 'ai_tool');
insert into item(name, category) values ('Puppetry', 'ai_tool');
insert into item(name, category) values ('QR Galaxy', 'ai_tool');
insert into item(name, category) values ('Qodex', 'ai_tool');
insert into item(name, category) values ('Quickads', 'ai_tool');
insert into item(name, category) values ('Quillbot', 'ai_tool');
insert into item(name, category) values ('Quizgecko', 'ai_tool');
insert into item(name, category) values ('REimagineHome', 'ai_tool');
insert into item(name, category) values ('RankIQ', 'ai_tool');
insert into item(name, category) values ('RankPress', 'ai_tool');
insert into item(name, category) values ('Rask', 'ai_tool');
insert into item(name, category) values ('Recast', 'ai_tool');
insert into item(name, category) values ('Recast Studio', 'ai_tool');
insert into item(name, category) values ('Recut', 'ai_tool');
insert into item(name, category) values ('Reelio', 'ai_tool');
insert into item(name, category) values ('Referral Factory', 'ai_tool');
insert into item(name, category) values ('Reflect', 'ai_tool');
insert into item(name, category) values ('Remove BG', 'ai_tool');
insert into item(name, category) values ('RenderLion', 'ai_tool');
insert into item(name, category) values ('RepliQ', 'ai_tool');
insert into item(name, category) values ('Replit', 'ai_tool');
insert into item(name, category) values ('RepublicLabs', 'ai_tool');
insert into item(name, category) values ('Research Studio', 'ai_tool');
insert into item(name, category) values ('Riku', 'ai_tool');
insert into item(name, category) values ('Riverside Audio Transcription', 'ai_tool');
insert into item(name, category) values ('Runway ML', 'ai_tool');
insert into item(name, category) values ('Rytr', 'ai_tool');
insert into item(name, category) values ('SE Ranking', 'ai_tool');
insert into item(name, category) values ('SEO GPT', 'ai_tool');
insert into item(name, category) values ('SEOPress', 'ai_tool');
insert into item(name, category) values ('SEOmatic', 'ai_tool');
insert into item(name, category) values ('SUPERMACHINE', 'ai_tool');
insert into item(name, category) values ('Safuri', 'ai_tool');
insert into item(name, category) values ('Sanebox', 'ai_tool');
insert into item(name, category) values ('Scribe', 'ai_tool');
insert into item(name, category) values ('Secta Labs', 'ai_tool');
insert into item(name, category) values ('Semrush outline builder', 'ai_tool');
insert into item(name, category) values ('Sharp API', 'ai_tool');
insert into item(name, category) values ('Shortspilot', 'ai_tool');
insert into item(name, category) values ('Shuffll', 'ai_tool');
insert into item(name, category) values ('Simple Phones', 'ai_tool');
insert into item(name, category) values ('Simplified', 'ai_tool');
insert into item(name, category) values ('SiteSpeakAI', 'ai_tool');
insert into item(name, category) values ('Skybox Lab', 'ai_tool');
insert into item(name, category) values ('Snoooz', 'ai_tool');
insert into item(name, category) values ('SocialBee', 'ai_tool');
insert into item(name, category) values ('Softr AI', 'ai_tool');
insert into item(name, category) values ('SongR', 'ai_tool');
insert into item(name, category) values ('Sonic Link', 'ai_tool');
insert into item(name, category) values ('Soofy', 'ai_tool');
insert into item(name, category) values ('Soundraw', 'ai_tool');
insert into item(name, category) values ('Soundverse', 'ai_tool');
insert into item(name, category) values ('Speak AI', 'ai_tool');
insert into item(name, category) values ('Speechify', 'ai_tool');
insert into item(name, category) values ('Spikes Studio', 'ai_tool');
insert into item(name, category) values ('Squirrly SEO', 'ai_tool');
insert into item(name, category) values ('StealthGPT', 'ai_tool');
insert into item(name, category) values ('Steve AI', 'ai_tool');
insert into item(name, category) values ('StoryNest', 'ai_tool');
insert into item(name, category) values ('Submagic', 'ai_tool');
insert into item(name, category) values ('SudoWrite', 'ai_tool');
insert into item(name, category) values ('Super', 'ai_tool');
insert into item(name, category) values ('Surfer SEO', 'ai_tool');
insert into item(name, category) values ('Syllaby', 'ai_tool');
insert into item(name, category) values ('Synthesia', 'ai_tool');
insert into item(name, category) values ('Sysarchitect', 'ai_tool');
insert into item(name, category) values ('Tabnine', 'ai_tool');
insert into item(name, category) values ('Tailwind Ghostwriter', 'ai_tool');
insert into item(name, category) values ('TalkPal', 'ai_tool');
insert into item(name, category) values ('Talkio', 'ai_tool');
insert into item(name, category) values ('Taskade', 'ai_tool');
insert into item(name, category) values ('TeacherMatic', 'ai_tool');
insert into item(name, category) values ('TeamSmart AI', 'ai_tool');
insert into item(name, category) values ('Text Cortex', 'ai_tool');
insert into item(name, category) values ('Thoughtly', 'ai_tool');
insert into item(name, category) values ('TikTok', 'ai_tool');
insert into item(name, category) values ('Toasty AI', 'ai_tool');
insert into item(name, category) values ('Todoist AI Assistant', 'ai_tool');
insert into item(name, category) values ('Trinka AI', 'ai_tool');
insert into item(name, category) values ('Tripo AI', 'ai_tool');
insert into item(name, category) values ('TubeBuddy', 'ai_tool');
insert into item(name, category) values ('Tugan', 'ai_tool');
insert into item(name, category) values ('TurnCage', 'ai_tool');
insert into item(name, category) values ('Tweet Hunter', 'ai_tool');
insert into item(name, category) values ('TweetMonk', 'ai_tool');
insert into item(name, category) values ('Typefully', 'ai_tool');
insert into item(name, category) values ('Typeshare', 'ai_tool');
insert into item(name, category) values ('Typing Mind', 'ai_tool');
insert into item(name, category) values ('Upmetrics', 'ai_tool');
insert into item(name, category) values ('User Evaluation', 'ai_tool');
insert into item(name, category) values ('VEED', 'ai_tool');
insert into item(name, category) values ('Validly', 'ai_tool');
insert into item(name, category) values ('Vecteezy AI', 'ai_tool');
insert into item(name, category) values ('Vidalgo', 'ai_tool');
insert into item(name, category) values ('VideoGen', 'ai_tool');
insert into item(name, category) values ('VideoIdeas.ai', 'ai_tool');
insert into item(name, category) values ('Vidgen', 'ai_tool');
insert into item(name, category) values ('Vidnoz', 'ai_tool');
insert into item(name, category) values ('Viralkit', 'ai_tool');
insert into item(name, category) values ('Visily', 'ai_tool');
insert into item(name, category) values ('Visme AI', 'ai_tool');
insert into item(name, category) values ('Vista Social', 'ai_tool');
insert into item(name, category) values ('Voluum', 'ai_tool');
insert into item(name, category) values ('Wavel AI', 'ai_tool');
insert into item(name, category) values ('Waxwing', 'ai_tool');
insert into item(name, category) values ('WebWave', 'ai_tool');
insert into item(name, category) values ('WellSaid Labs', 'ai_tool');
insert into item(name, category) values ('WindsorAI', 'ai_tool');
insert into item(name, category) values ('Winston ai', 'ai_tool');
insert into item(name, category) values ('Wonderplan', 'ai_tool');
insert into item(name, category) values ('Wondershare Virbo', 'ai_tool');
insert into item(name, category) values ('Wondershare VirtuLook', 'ai_tool');
insert into item(name, category) values ('Writers brew', 'ai_tool');
insert into item(name, category) values ('Writesonic', 'ai_tool');
insert into item(name, category) values ('Yaara', 'ai_tool');
insert into item(name, category) values ('Yera', 'ai_tool');
insert into item(name, category) values ('grokai', 'ai_tool');
insert into item(name, category) values ('deepseek', 'ai_tool');
insert into item(name, category) values ('blackboxAI', 'ai_tool');
insert into item(name, category) values ('copyAI', 'ai_tool');
insert into item(name, category) values ('synthesia', 'ai_tool');
insert into item(name, category) values ('MidJourney', 'ai_tool');
insert into item(name, category) values ('Claude', 'ai_tool');
insert into item(name, category) values ('WordTune', 'ai_tool');
insert into item(name, category) values ('Runway', 'ai_tool');
insert into item(name, category) values ('YourMove AI', 'ai_tool');
insert into item(name, category) values ('Zentask', 'ai_tool');
insert into item(name, category) values ('Zigpoll', 'ai_tool');
insert into item(name, category) values ('Zyro', 'ai_tool');
insert into item(name, category) values ('aiApply', 'ai_tool');
insert into item(name, category) values ('aiCarousels', 'ai_tool');
insert into item(name, category) values ('guidde', 'ai_tool');
insert into item(name, category) values ('iApply', 'ai_tool');
insert into item(name, category) values ('iSpring Page', 'ai_tool');
insert into item(name, category) values ('n8n', 'ai_tool');
insert into item(name, category) values ('tinyEinstein', 'ai_tool');
insert into item(name, category) values ('tl;dv', 'ai_tool');
insert into item(name, category) values ('chatgpt43', 'ai_tool');
insert into item(name, category) values ('GROK', 'ai_tool');
insert into item(name, category) values ('SKYNET', 'ai_tool');
insert into item(name, category) values ('Midjourney', 'ai_tool');
insert into item(name, category) values ('Kling AI', 'ai_tool');
insert into item(name, category) values ('QUILTBOT', 'ai_tool');
insert into item(name, category) values ('QUILTBOT 2.0', 'ai_tool');
insert into item(name, category) values ('vnoyd', 'ai_tool');
insert into item(name, category) values ('chatgpt2', 'ai_tool');
insert into item(name, category) values ('chatgpt3', 'ai_tool');
insert into item(name, category) values ('notebooklm', 'ai_tool');
insert into item(name, category) values ('chatgpt13', 'ai_tool');
insert into item(name, category) values ('chatgpt16', 'ai_tool');
insert into item(name, category) values ('DALL.E', 'ai_tool');
insert into item(name, category) values ('GAMMA.AI', 'ai_tool');
insert into item(name, category) values ('chatgpt50', 'ai_tool');
insert into item(name, category) values ('perplexity', 'ai_tool');
insert into item(name, category) values ('chatgpt40', 'ai_tool');
insert into item(name, category) values ('Jasper Ai', 'ai_tool');
insert into item(name, category) values ('AgentGPT', 'ai_tool');
insert into item(name, category) values ('cluade', 'ai_tool');
insert into item(name, category) values ('AI Dating', 'ai_tool');
insert into item(name, category) values ('Leonardo', 'ai_tool');
insert into item(name, category) values ('Gemini', 'ai_tool');
insert into item(name, category) values ('Pika Labs', 'ai_tool');
insert into item(name, category) values ('Boomy', 'ai_tool');
insert into item(name, category) values ('stealth writer', 'ai_tool');
insert into item(name, category) values ('Copilot', 'ai_tool');
insert into item(name, category) values ('FATHOM', 'ai_tool');
insert into item(name, category) values ('AIVA', 'ai_tool');

insert into item(name, category) values ('Gemischtes Hack', 'podcast');
insert into item(name, category) values ('Mordlust', 'podcast');
insert into item(name, category) values ('Kaulitz Hills - Senf aus Hollywood', 'podcast');
insert into item(name, category) values ('Fest & Flauschig', 'podcast');
insert into item(name, category) values ('MORD AUF EX', 'podcast');
insert into item(name, category) values ('LANZ & PRECHT', 'podcast');
insert into item(name, category) values ('Baywatch Berlin', 'podcast');
insert into item(name, category) values ('Offline + Ehrlich', 'podcast');
insert into item(name, category) values ('Verbrechen', 'podcast');
insert into item(name, category) values ('Dick & Doof', 'podcast');
insert into item(name, category) values ('Hobbylos', 'podcast');
insert into item(name, category) values ('Edeltalk - mit Dominik & Kevin', 'podcast');
insert into item(name, category) values ('Lewinray ', 'podcast');
insert into item(name, category) values ('Wissen Weekly', 'podcast');
insert into item(name, category) values ('Die Nervigen', 'podcast');
insert into item(name, category) values ('Copa TS', 'podcast');
insert into item(name, category) values ('Aktenzeichen XY… Unvergessene Verbrechen', 'podcast');
insert into item(name, category) values ('Simplicissimus', 'podcast');
insert into item(name, category) values ('Henke''s Corner', 'podcast');
insert into item(name, category) values ('Clare on Air', 'podcast');
insert into item(name, category) values ('Lage der Nation - der Politik-Podcast aus Berlin', 'podcast');
insert into item(name, category) values ('Hotel Matze', 'podcast');
insert into item(name, category) values ('Was jetzt?', 'podcast');
insert into item(name, category) values ('RONZHEIMER.', 'podcast');
insert into item(name, category) values ('Verbrechen von nebenan: True Crime aus der Nachbarschaft', 'podcast');
insert into item(name, category) values ('Apokalypse & Filterkaffee', 'podcast');
insert into item(name, category) values ('Hoss & Hopf', 'podcast');
insert into item(name, category) values ('UNFASSBAR – ein Simplicissimus Podcast', 'podcast');
insert into item(name, category) values ('Die Nachrichten', 'podcast');
insert into item(name, category) values ('Tim Gabel Podcast', 'podcast');
insert into item(name, category) values ('Talk ohne Gast', 'podcast');
insert into item(name, category) values ('Zum Scheitern Verurteilt', 'podcast');
insert into item(name, category) values ('Kaffee mit Zitrone ', 'podcast');
insert into item(name, category) values ('Kurt Krömer - Feelings', 'podcast');
insert into item(name, category) values ('Wissen mit Johnny', 'podcast');
insert into item(name, category) values ('Mord am Mittwoch - True Crime', 'podcast');
insert into item(name, category) values ('Keine Echten Männer', 'podcast');
insert into item(name, category) values ('laserluca', 'podcast');
insert into item(name, category) values ('Auf den Punkt', 'podcast');
insert into item(name, category) values ('Serienkiller - Mörder und ihre Geschichten', 'podcast');
insert into item(name, category) values ('ViscaTabak - Der Fußball Podcast', 'podcast');
insert into item(name, category) values ('Handelsblatt Morning Briefing - News aus Wirtschaft, Politik und Finanzen', 'podcast');
insert into item(name, category) values ('G Spot mit Stefanie Giesinger', 'podcast');
insert into item(name, category) values ('PLOT HOUSE', 'podcast');
insert into item(name, category) values ('Bayern 3 True Crime - Schuld und Unschuld', 'podcast');
insert into item(name, category) values ('Geschichten aus der Geschichte', 'podcast');
insert into item(name, category) values ('ARD Crime Time – Der True Crime Podcast', 'podcast');
insert into item(name, category) values ('DRINNIES', 'podcast');
insert into item(name, category) values ('Der Sophie Passmann Podcast', 'podcast');
insert into item(name, category) values ('Freundschaft Minus', 'podcast');
insert into item(name, category) values ('Das Politikteil', 'podcast');
insert into item(name, category) values ('Machtwechsel – mit Dagmar Rosenfeld und Robin Alexander', 'podcast');
insert into item(name, category) values ('50+2 - Der Fussballpodcast mit Nico & Niklas', 'podcast');
insert into item(name, category) values ('15 Minuten. Der tagesschau-Podcast am Morgen', 'podcast');
insert into item(name, category) values ('Rick Azas', 'podcast');
insert into item(name, category) values ('Benx', 'podcast');
insert into item(name, category) values ('El Margo', 'podcast');
insert into item(name, category) values ('Bratwurst und Baklava - mit Özcan Cosar und Bastian Bielendorfer', 'podcast');
insert into item(name, category) values ('Das Wissen | SWR', 'podcast');
insert into item(name, category) values ('Zwei Vermengte', 'podcast');
insert into item(name, category) values ('tagesschau in 100 Sekunden (Audio-Podcast)', 'podcast');
insert into item(name, category) values ('Alles gesagt?', 'podcast');
insert into item(name, category) values ('Girls Girls ', 'podcast');
insert into item(name, category) values ('{ungeskriptet} - Gespräche, die dich weiter bringen', 'podcast');
insert into item(name, category) values ('0630 - der News-Podcast', 'podcast');
insert into item(name, category) values ('Politik mit Anne Will', 'podcast');
insert into item(name, category) values ('OK, America?', 'podcast');
insert into item(name, category) values ('Die Deutschen Podcast', 'podcast');
insert into item(name, category) values ('So bin ich eben! Stefanie Stahls Psychologie-Podcast für alle "Normalgestörten"', 'podcast');
insert into item(name, category) values ('Reeze', 'podcast');
insert into item(name, category) values ('Schwarze Akte - True Crime', 'podcast');
insert into item(name, category) values ('Psychologie to go!', 'podcast');
insert into item(name, category) values ('Ziemlich beste Fremde', 'podcast');
insert into item(name, category) values ('Mit den Waffeln einer Frau', 'podcast');
insert into item(name, category) values ('Der Tag', 'podcast');
insert into item(name, category) values ('Alles auf Aktien – Die täglichen Finanzen-News', 'podcast');
insert into item(name, category) values ('too many tabs – der Podcast', 'podcast');
insert into item(name, category) values ('11KM: der tagesschau-Podcast', 'podcast');
insert into item(name, category) values ('Betreutes Fühlen', 'podcast');
insert into item(name, category) values ('Eine Stunde History - Deutschlandfunk Nova', 'podcast');
insert into item(name, category) values ('Was bisher geschah - Geschichtspodcast', 'podcast');
insert into item(name, category) values ('Einfach mal Luppen', 'podcast');
insert into item(name, category) values ('Kalk & Welk - Die fabelhaften Boomer Boys', 'podcast');
insert into item(name, category) values ('Äffchen mit Käffchen', 'podcast');
insert into item(name, category) values ('Hazel Thomas Hörerlebnis', 'podcast');
insert into item(name, category) values ('CheckPod - Der Podcast mit Checker Tobi', 'podcast');
insert into item(name, category) values ('Quarks Daily', 'podcast');
insert into item(name, category) values ('TRUE LOVE', 'podcast');
insert into item(name, category) values ('OMR Podcast', 'podcast');
insert into item(name, category) values ('FOOTBALL BROMANCE', 'podcast');
insert into item(name, category) values ('Quarks Science Cops', 'podcast');
insert into item(name, category) values ('tagesschau (Audio-Podcast)', 'podcast');
insert into item(name, category) values ('Acht Milliarden - Der Auslandspodcast des SPIEGEL', 'podcast');
insert into item(name, category) values ('Im Visier – Verbrecherjagd in Berlin und Brandenburg', 'podcast');
insert into item(name, category) values ('Eyes in the Dark', 'podcast');
insert into item(name, category) values ('Gysi gegen Guttenberg – Der Deutschland Podcast', 'podcast');
insert into item(name, category) values ('BLIND DATING 💔 mit Ceddo', 'podcast');
insert into item(name, category) values ('Skandal, Skandal', 'podcast');
insert into item(name, category) values ('life is felicious', 'podcast');
insert into item(name, category) values ('Darwin gefällt das', 'podcast');
insert into item(name, category) values ('Julia Leischik: Spurlos', 'podcast');
insert into item(name, category) values ('tomatolix', 'podcast');
insert into item(name, category) values ('F.A.Z. Frühdenker - Die Nachrichten am Morgen', 'podcast');
insert into item(name, category) values ('The Joe Rogan Experience', 'podcast');
insert into item(name, category) values ('Paarspektiven', 'podcast');
insert into item(name, category) values ('Jung & Naiv', 'podcast');
insert into item(name, category) values ('5 Minuten Harry Podcast von Coldmirror', 'podcast');
insert into item(name, category) values ('Stahl aber herzlich – Der Psychotherapie-Podcast mit Stefanie Stahl', 'podcast');
insert into item(name, category) values ('Ohne Bewährung - True Crime von hier', 'podcast');
insert into item(name, category) values ('stern Crime - Spurensuche', 'podcast');
insert into item(name, category) values ('The Pioneer Briefing', 'podcast');
insert into item(name, category) values ('Gnu', 'podcast');
insert into item(name, category) values ('Papaplatte', 'podcast');
insert into item(name, category) values ('Niemand muss ein Promi sein - Deutschlands Nr. 1 Gossip-Podcast!', 'podcast');
insert into item(name, category) values ('Table Today', 'podcast');
insert into item(name, category) values ('Gefühlte Fakten', 'podcast');
insert into item(name, category) values ('EinfachGustaf | Dein Minecraft Kanal!', 'podcast');
insert into item(name, category) values ('Alex Freerun', 'podcast');
insert into item(name, category) values ('Raum & Zeit', 'podcast');
insert into item(name, category) values ('dudes.', 'podcast');
insert into item(name, category) values ('Geld für die Welt', 'podcast');
insert into item(name, category) values ('happy, holy & confident® Dein Podcast fürs Herz und den Verstand', 'podcast');
insert into item(name, category) values ('Kampf der Unternehmen', 'podcast');
insert into item(name, category) values ('F.A.Z. Podcast für Deutschland', 'podcast');
insert into item(name, category) values ('Aha! Zehn Minuten Alltags-Wissen', 'podcast');
insert into item(name, category) values ('Feel The News', 'podcast');
insert into item(name, category) values ('Handelsblatt Today - Der Finanzpodcast mit News zu Börse, Aktien und Geldanlage', 'podcast');
insert into item(name, category) values ('FUSSBALL MML', 'podcast');
insert into item(name, category) values ('Johannesmlz', 'podcast');
insert into item(name, category) values ('Ehrenwort - Ein Podcast über Skandale', 'podcast');
insert into item(name, category) values ('Verbrechen der Vergangenheit', 'podcast');
insert into item(name, category) values ('Zeigler & Köster - Der Fußball-Podcast von 11FREUNDE', 'podcast');
insert into item(name, category) values ('Streitkräfte und Strategien', 'podcast');
insert into item(name, category) values ('DAS PODCAST UFO', 'podcast');
insert into item(name, category) values ('Nie & Immer', 'podcast');
insert into item(name, category) values ('CALCIO BERLIN', 'podcast');
insert into item(name, category) values ('Mensch! Promi Skandale und ihre Geschichte', 'podcast');
insert into item(name, category) values ('Reif ist live – Fußball Talk von BILD', 'podcast');
insert into item(name, category) values ('Besser als Sex', 'podcast');
insert into item(name, category) values ('Firewall: Jedes System hat eine Schwachstelle', 'podcast');
insert into item(name, category) values ('Beste Freundinnen', 'podcast');
insert into item(name, category) values ('Dieser eine Moment – Der Podcast mit Philipp Fleiter', 'podcast');
insert into item(name, category) values ('Youtify', 'podcast');
insert into item(name, category) values ('POLITICO Berlin Playbook', 'podcast');
insert into item(name, category) values ('Pferdeschwänze', 'podcast');
insert into item(name, category) values ('Nachmittagsjause mit Ankat', 'podcast');
insert into item(name, category) values ('Wahre Verbrechen - True Crime Podcast', 'podcast');
insert into item(name, category) values ('OHNE AKTIEN WIRD SCHWER - Tägliche Börsen-News', 'podcast');
insert into item(name, category) values ('Der Politikpodcast', 'podcast');
insert into item(name, category) values ('Was die Woche wichtig war – Der funk-Podcast', 'podcast');
insert into item(name, category) values ('PietCast', 'podcast');
insert into item(name, category) values ('Dark Matters – Geheimnisse der Geheimdienste', 'podcast');
insert into item(name, category) values ('Alliteration Am Arsch', 'podcast');
insert into item(name, category) values ('Sternstunde Philosophie', 'podcast');
insert into item(name, category) values ('Tatort Deutschland – Wahre Kriminalfälle und Verbrechen', 'podcast');
insert into item(name, category) values ('Weird Crimes', 'podcast');
insert into item(name, category) values ('Die Lage', 'podcast');
insert into item(name, category) values ('Im Bett mit Anna-Maria und Anis Ferchichi - Der Bushido Podcast', 'podcast');
insert into item(name, category) values ('Brawler''s World', 'podcast');
insert into item(name, category) values ('Jay & Arya - Der eigentlich ganz gute Podcast', 'podcast');
insert into item(name, category) values ('Adoptivbrüder – mit Hannes & Jeremy', 'podcast');
insert into item(name, category) values ('Das wahre Leben – Der NACHTCAFÉ Podcast', 'podcast');
insert into item(name, category) values ('Puppies and Crime', 'podcast');
insert into item(name, category) values ('The Diary Of A CEO with Steven Bartlett', 'podcast');
insert into item(name, category) values ('Wie geht''s? mit Robin Gosens', 'podcast');
insert into item(name, category) values ('Terra X History - Der Podcast', 'podcast');
insert into item(name, category) values ('Macht und Millionen – Der Podcast über echte Wirtschaftskrimis', 'podcast');
insert into item(name, category) values ('Deutschland3000 - ''ne gute Stunde mit Eva Schulz', 'podcast');
insert into item(name, category) values ('Lästerschwestern', 'podcast');
insert into item(name, category) values ('Was tun, Herr General? - Der Podcast zum Ukraine-Krieg', 'podcast');
insert into item(name, category) values ('CRIME TIME', 'podcast');
insert into item(name, category) values ('Finanzfluss Podcast', 'podcast');
insert into item(name, category) values ('Paula Lieben Lernen', 'podcast');
insert into item(name, category) values ('Stammplatz – Fußball News täglich', 'podcast');
insert into item(name, category) values ('Phrasenmäher - Fußball Talk mit Henning Feindt und André Albers', 'podcast');
insert into item(name, category) values ('Haschimitenfürst – Der Bobcast', 'podcast');
insert into item(name, category) values ('Ulle & Rick', 'podcast');
insert into item(name, category) values ('Theresa Kirchner', 'podcast');
insert into item(name, category) values ('Sekten & Kulte - Im Namen des Bösen', 'podcast');
insert into item(name, category) values ('Insolito - Nur ein weiterer TrueCrime-Podcast', 'podcast');
insert into item(name, category) values ('Weltspiegel Podcast', 'podcast');
insert into item(name, category) values ('THE BIG HEAD JUAN SHOW (NSFW)', 'podcast');
insert into item(name, category) values ('Einschlafen mit Hogwarts', 'podcast');
insert into item(name, category) values ('Stimmen im Kopf - True-Crime / Mystery Podcast', 'podcast');
insert into item(name, category) values ('Down Set Talk! - Der NFL Podcast von RTL', 'podcast');
insert into item(name, category) values ('His2Go - Geschichte Podcast', 'podcast');
insert into item(name, category) values ('Die Drei Rabauken', 'podcast');
insert into item(name, category) values ('Augstein & Blome', 'podcast');
insert into item(name, category) values ('maischberger. der podcast', 'podcast');
insert into item(name, category) values ('Dings und Bums', 'podcast');
insert into item(name, category) values ('Alle meine Eltern – Der Real Talk mit Evelyn Weigert', 'podcast');
insert into item(name, category) values ('Handelsblatt Crime - spannende Streitfälle der deutschen Wirtschaft', 'podcast');
insert into item(name, category) values ('Spitzengespräch', 'podcast');
insert into item(name, category) values ('MutterSöhnchen', 'podcast');
insert into item(name, category) values ('Einschlafen mit Wikipedia', 'podcast');
insert into item(name, category) values ('Science Crimes', 'podcast');
insert into item(name, category) values ('Make Economy Great Again', 'podcast');
insert into item(name, category) values ('Alman Arabica', 'podcast');
insert into item(name, category) values ('Sicherheitshalber', 'podcast');
insert into item(name, category) values ('ZEIT WISSEN. Woher weißt Du das?', 'podcast');
